<?php
 
_verb_register_tag('a', array('handler' => '_verb_render_a', 'html' => 'a'));
_verb_register_tag('a_if', array('handler' => '_verb_render_a_if', 'html' => 'a'));
_verb_register_tag('asset', array('handler' => '_verb_render_asset'));
_verb_register_tag('captcha', array('handler' => '_verb_render_captcha', 'html' => 'input'));
_verb_register_tag('cdn', array('handler' => '_verb_render_cdn'));
_verb_register_tag('checkbox', array('handler' => '_verb_render_checkbox', 'html' => 'input'));
_verb_register_tag('collection', array('handler' => '_verb_render_collection', 'required' => array("path")));
_verb_register_tag('country_select', array('handler' => '_verb_render_country_select', 'html' => 'select'));
_verb_register_tag('create', array('callback' => '_verb_callback_create', 'handler' => '_verb_render_create', 'required' => array("path"), 'filename' => 'callback.php'));
_verb_register_tag('date_select', array('handler' => '_verb_render_date_select', 'html' => 'select'));
_verb_register_tag('date_selection', array('handler' => '_verb_render_pagination', 'html' => 'a', 'required' => array("date_field","path")));
_verb_register_tag('debug', array('handler' => '_verb_render_debug'));
_verb_register_tag('disqus', array('handler' => '_verb_render_disqus', 'required' => array("shortname")));
_verb_register_tag('divider', array('handler' => '_verb_render_divider'));
_verb_register_tag('else', array('handler' => '_verb_render_else'));
_verb_register_tag('elseif', array('handler' => '_verb_render_elseif'));
_verb_register_tag('facebook_comments', array('handler' => '_verb_render_facebook_comments', 'required' => array('appid')));
_verb_register_tag('facebook_like', array('handler' => '_verb_render_facebook_like'));
_verb_register_tag('file', array('callback' => '_verb_callback_file', 'handler' => '_verb_render_file', 'html' => 'a', 'required' => array("path"), 'filename' => 'callback.php'));
_verb_register_tag('file_field', array('handler' => '_verb_render_file_field', 'html' => 'input'));
_verb_register_tag('fileurl', array('handler' => '_verb_render_fileurl', 'required' => array("path")));
_verb_register_tag('flash', array('handler' => '_verb_render_flash'));
_verb_register_tag('form', array('handler' => '_verb_render_form', 'html' => 'form', 'required' => array()));
_verb_register_tag('formmail', array('callback' => '_verb_callback_formmail', 'handler' => '_verb_render_formmail', 'html' => 'form', 'required' => array("to"), 'filename' => 'callback.php'));
_verb_register_tag('fragment', array('handler' => '_verb_render_fragment'));
_verb_register_tag('gravatar', array('handler' => '_verb_render_gravatar', 'html' => 'img', 'required' => array("email")));
_verb_register_tag('hidden_field', array('handler' => '_verb_render_hidden_field', 'html' => 'input'));
_verb_register_tag('if', array('handler' => '_verb_render_if'));
_verb_register_tag('if_backstage', array('handler' => '_verb_render_if_backstage'));
_verb_register_tag('if_paginate', array('handler' => '_verb_render_if_paginate'));
_verb_register_tag('if_time', array('handler' => '_verb_render_if_time'));
_verb_register_tag('img', array('handler' => '_verb_render_img', 'html' => 'img'));
_verb_register_tag('imurl', array('handler' => '_verb_render_img'));
_verb_register_tag('module', array('handler' => '_verb_render_template', 'required' => array("filename")));
_verb_register_tag('nested_collection', array('handler' => '_verb_render_nested_collection', 'required' => array("path")));
_verb_register_tag('nested_divider', array('handler' => '_verb_render_divider'));
_verb_register_tag('newsletter', array('callback' => '_verb_callback_newsletter', 'handler' => '_verb_render_newsletter', 'html' => 'form', 'required' => array("code"), 'filename' => 'callback.php'));
_verb_register_tag('nowidows', array('handler' => '_verb_render_nowidows'));
_verb_register_tag('option_select', array('handler' => '_verb_render_option_select', 'html' => 'select', 'required' => array("fields","name","path")));
_verb_register_tag('pdf', array('handler' => '_verb_render_pdf', 'required' => array()));
_verb_register_tag('pagination', array('handler' => '_verb_render_pagination', 'html' => 'a'));
_verb_register_tag('password_field', array('handler' => '_verb_render_password_field', 'html' => 'input'));
_verb_register_tag('php', array('handler' => '_verb_render_php'));
_verb_register_tag('radio', array('handler' => '_verb_render_radio', 'html' => 'input'));
_verb_register_tag('repeat', array('handler' => '_verb_render_repeat'));
_verb_register_tag('require_permalink', array('handler' => '_verb_render_require_permalink', 'required' => array()));
_verb_register_tag('require_ssl', array('handler' => '_verb_render_require_ssl', 'required' => array()));
_verb_register_tag('rss', array('handler' => '_verb_render_rss', 'required' => array("path","title","description")));
_verb_register_tag('section', array('handler' => '_verb_render_section', 'required' => array("path")));
_verb_register_tag('select', array('handler' => '_verb_render_select', 'html' => 'select'));
_verb_register_tag('set', array('handler' => '_verb_render_set', 'required' => array('name')));
_verb_register_tag('set_default', array('handler' => '_verb_render_set_default', 'required' => array('name')));
_verb_register_tag('session_dump', array('handler' => '_verb_render_session_dump', 'required' => array('key')));
_verb_register_tag('site_seal', array('handler' => '_verb_render_site_seal'));
_verb_register_tag('state_select', array('handler' => '_verb_render_state_select', 'html' => 'select'));
_verb_register_tag('template', array('handler' => '_verb_render_template', 'required' => array("filename")));
_verb_register_tag('text', array('handler' => '_verb_render_text', 'required' => array()));
_verb_register_tag('text_area', array('handler' => '_verb_render_text_area', 'html' => 'textarea'));
_verb_register_tag('text_field', array('handler' => '_verb_render_text_field', 'html' => 'input'));
_verb_register_tag('unsubscribe', array('handler' => '_verb_render_unsubscribe'));
_verb_register_tag('update', array('callback' => '_verb_callback_update', 'handler' => '_verb_render_update', 'filename' => 'callback.php'));
_verb_register_tag('video', array('handler' => '_verb_render_video'));
_verb_register_tag('yield', array('handler' => '_verb_render_yield'));
_verb_register_tag('zip', array('callback' => '_verb_callback_zip', 'handler' => '_verb_render_zip', 'html' => 'a', 'filename' => 'callback.php'));
_verb_register_tag('store_add_to_cart', array('callback' => '_verb_store_callback_add_to_cart', 'handler' => '_verb_store_render_add_to_cart', 'html' => 'form'));
_verb_register_tag('store_address_delete', array('callback' => '_verb_store_callback_address_delete', 'html' => 'a', 'handler' => '_verb_store_render_address_delete'));
_verb_register_tag('store_address_select', array('callback' => '_verb_store_callback_address_select', 'handler' => '_verb_store_render_address_select', 'html' => 'select'));
_verb_register_tag('store_addresses', array('handler' => '_verb_store_render_addresses'));
_verb_register_tag('store_bundled_item', array('handler' => '_verb_store_render_bundled_item'));
_verb_register_tag('store_cart', array('callback' => '_verb_store_callback_cart', 'handler' => '_verb_store_render_cart', 'html' => 'form'));
_verb_register_tag('store_cart_items', array('handler' => '_verb_store_render_cart_items'));
_verb_register_tag('store_cart_discount', array('handler' => '_verb_store_render_cart_discount'));
_verb_register_tag('store_cart_shipping', array('handler' => '_verb_store_render_cart_shipping'));
_verb_register_tag('store_cart_subtotal', array('handler' => '_verb_store_render_cart_subtotal'));
_verb_register_tag('store_cart_tax', array('handler' => '_verb_store_render_cart_tax'));
_verb_register_tag('store_cart_total', array('handler' => '_verb_store_render_cart_total'));
_verb_register_tag('store_checkout', array('callback' => '_verb_store_callback_checkout', 'handler' => '_verb_store_render_checkout', 'html' => 'form', 'required' => array("redirect","register_page")));
_verb_register_tag('store_credit_card', array('handler' => '_verb_store_render_if_credit_card'));
_verb_register_tag('store_credit_card_select', array('handler' => '_verb_store_render_credit_card_select', 'html' => 'select'));
_verb_register_tag('store_currency', array('handler' => '_verb_store_render_currency'));
_verb_register_tag('store_currency_select', array('callback' => '_verb_store_callback_currency_select', 'handler' => '_verb_store_render_currency_select', 'html' => 'select'));
_verb_register_tag('store_discount', array('callback' => '_verb_store_callback_discount', 'handler' => '_verb_store_render_discount', 'html' => 'form'));
_verb_register_tag('store_forgot', array('callback' => '_verb_store_callback_forgot', 'handler' => '_verb_store_render_forgot', 'html' => 'form'));
_verb_register_tag('store_if_bank_transfer', array('handler' => '_verb_store_render_if_bank_transfer'));
_verb_register_tag('store_if_check', array('handler' => '_verb_store_render_if_check'));
_verb_register_tag('store_if_credit_card', array('handler' => '_verb_store_render_if_credit_card'));
_verb_register_tag('store_if_currency', array('handler' => '_verb_store_render_if_currency'));
_verb_register_tag('store_if_digital_downloads', array('handler' => '_verb_store_render_if_digital_downloads'));
_verb_register_tag('store_if_discount', array('handler' => '_verb_store_render_if_discount'));
_verb_register_tag('store_if_field_overridden', array('handler' => '_verb_store_render_if_field_overridden', 'required' => array('field', 'options_collection')));
_verb_register_tag('store_if_in_cart', array('handler' => '_verb_store_render_if_in_cart'));
_verb_register_tag('store_if_logged_in', array('handler' => '_verb_store_render_if_logged_in'));
_verb_register_tag('store_if_money_order', array('handler' => '_verb_store_render_if_money_order'));
_verb_register_tag('store_if_pay_in_store', array('handler' => '_verb_store_render_if_pay_in_store'));
_verb_register_tag('store_if_paypal', array('handler' => '_verb_store_render_if_paypal'));
_verb_register_tag('store_if_paypal_checkout', array('handler' => '_verb_store_render_if_paypal_checkout'));
_verb_register_tag('store_if_paypal_express_checkout', array('handler' => '_verb_store_render_if_paypal_express_checkout'));
_verb_register_tag('store_if_recent_order_bank_transfer', array('handler' => '_verb_store_render_if_recent_order_bank_transfer'));
_verb_register_tag('store_if_recent_order_check', array('handler' => '_verb_store_render_if_recent_order_check'));
_verb_register_tag('store_if_recent_order_credit_card', array('handler' => '_verb_store_render_if_recent_order_credit_card'));
_verb_register_tag('store_if_recent_order_digital', array('handler' => '_verb_store_render_if_recent_order_digital'));
_verb_register_tag('store_if_recent_order_money_order', array('handler' => '_verb_store_render_if_recent_order_money_order'));
_verb_register_tag('store_if_recent_order_pay_in_store', array('handler' => '_verb_store_render_if_recent_order_pay_in_store'));
_verb_register_tag('store_if_recent_order_paypal', array('handler' => '_verb_store_render_if_recent_order_paypal'));
_verb_register_tag('store_if_recent_order_paypal_express_checkout', array('handler' => '_verb_store_render_if_recent_order_paypal_express_checkout'));
_verb_register_tag('store_if_shippable', array('handler' => '_verb_store_render_if_shippable'));
_verb_register_tag('store_if_tax', array('handler' => '_verb_store_render_if_tax'));
_verb_register_tag('store_if_user', array('handler' => '_verb_store_render_if_user'));
_verb_register_tag('store_item_if_discount', array('handler' => '_verb_store_render_item_if_discount'));
_verb_register_tag('store_item_price', array('handler' => '_verb_store_render_item_price'));
_verb_register_tag('store_login', array('callback' => '_verb_store_callback_login', 'handler' => '_verb_store_render_login', 'html' => 'form'));
_verb_register_tag('store_logout', array('callback' => '_verb_store_callback_logout', 'html' => 'a', 'handler' => '_verb_store_render_logout'));
_verb_register_tag('store_paypal_express_checkout', array('callback' => '_verb_store_callback_paypal_express_checkout', 'handler' => '_verb_store_render_paypal_express_checkout', 'html' => 'img'));
_verb_register_tag('store_payment_methods_select', array('callback' => '_verb_store_callback_payment_methods_select', 'handler' => '_verb_store_render_payment_methods_select', 'html' => 'select'));
_verb_register_tag('store_previous_order_items', array('handler' => '_verb_store_render_previous_order_items'));
_verb_register_tag('store_previous_order', array('handler' => '_verb_store_render_previous_order'));
_verb_register_tag('store_previous_orders', array('handler' => '_verb_store_render_previous_orders'));
_verb_register_tag('store_recent_order', array('handler' => '_verb_store_render_recent_order'));
_verb_register_tag('store_recent_order_items', array('handler' => '_verb_store_render_recent_order_items'));
_verb_register_tag('store_register', array('callback' => '_verb_store_callback_register', 'handler' => '_verb_store_render_register', 'html' => 'form', 'required' => array("redirect")));
_verb_register_tag('store_shipping_methods', array('handler' => '_verb_store_render_shipping_method'));
_verb_register_tag('store_shipping_methods_select', array('callback' => '_verb_store_callback_shipping_methods_select', 'handler' => '_verb_store_render_shipping_methods_select', 'html' => 'select'));
_verb_register_tag('store_user', array('handler' => '_verb_store_render_user'));
_verb_register_tag('users_forgot', array('callback' => '_verb_users_callback_forgot', 'handler' => '_verb_users_render_forgot', 'html' => 'form', 'required' => array("email_field","path","required"), 'filename' => 'users.php'));
_verb_register_tag('users_if_logged_in', array('handler' => '_verb_users_render_if_logged_in', 'filename' => 'users.php'));
_verb_register_tag('users_login', array('callback' => '_verb_users_callback_login', 'handler' => '_verb_users_render_login', 'html' => 'form', 'required' => array("path","required"), 'filename' => 'users.php'));
_verb_register_tag('users_logout', array('callback' => '_verb_users_callback_logout', 'html' => 'a', 'handler' => '_verb_users_render_logout', 'filename' => 'users.php'));
_verb_register_tag('users_register', array('callback' => '_verb_users_callback_register', 'handler' => '_verb_users_render_register', 'html' => 'form', 'required' => array("path","redirect"), 'filename' => 'users.php'));

echo "<pre>";
echo '$_VERB[\'tags\'] = ';
var_export($_VERB['tags']);
echo ";\n" . '$_VERB[\'callbacks\'] = ';
var_export($_VERB['callbacks']);
echo ";\n" . '$_VERB[\'form_items\'] = ';
var_export($_VERB['form_items']);
echo ";\n";
die();

?>